stages:
  - changelog:common
  - deploy:composer

changelog-common:
  stage: changelog:common
  image: 946241444896.dkr.ecr.eu-west-1.amazonaws.com/quadrant/devops/gitlab:tools-php-8.2.8-cli-20230724-1
  script:
    - /usr/local/bin/changelog.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-(dev|integration|qa|rc|release)/'

deploy-composer:
  image: 946241444896.dkr.ecr.eu-west-1.amazonaws.com/quadrant/devops/gitlab:tools-php-8.2.8-cli-20230724-1
  stage: deploy:composer
  script:
    - /usr/local/bin/add-gitlab-composer-registry.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-(dev|integration|qa|rc|release)/'
