#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace Boilerwork\Support\Services\FeesCalculator\ValueObjects\Currency;


class DataProvider
{

    /**
     * @var array iso4217, symbol
     */
    protected static $data = [
        ['ALL', 'Lek'],
        ['AFN', '؋'],
        ['ARS', '$'],
        ['AWG', 'ƒ'],
        ['AUD', '$'],
        ['AZN', 'ман'],
        ['BSD', '$'],
        ['BBD', '$'],
        ['BYR', 'p.'],
        ['BZD', 'BZ$'],
        ['BMD', '$'],
        ['BOB', '$b'],
        ['BAM', 'KM'],
        ['BWP', 'P'],
        ['BGN', 'лв'],
        ['BRL', 'R$'],
        ['BND', '$'],
        ['KHR', '៛'],
        ['CAD', '$'],
        ['KYD', '$'],
        ['CLP', '$'],
        ['CNY', '¥'],
        ['COP', '$'],
        ['CRC', '₡'],
        ['HRK', 'kn'],
        ['CUP', '₱'],
        ['CZK', 'Kč'],
        ['DKK', 'kr'],
        ['DOP', 'RD$'],
        ['XCD', '$'],
        ['EGP', '£'],
        ['SVC', '$'],
        ['EEK', 'kr'],
        ['EUR', '€'],
        ['FKP', '£'],
        ['FJD', '$'],
        ['GHC', '¢'],
        ['GIP', '£'],
        ['GTQ', 'Q'],
        ['GGP', '£'],
        ['GYD', '$'],
        ['HNL', 'L'],
        ['HKD', '$'],
        ['HUF', 'Ft'],
        ['ISK', 'kr'],
        ['INR', '₹'],
        ['IDR', 'Rp'],
        ['IRR', '﷼'],
        ['IMP', '£'],
        ['ILS', '₪'],
        ['JMD', 'J$'],
        ['JPY', '¥'],
        ['JEP', '£'],
        ['KZT', 'лв'],
        ['KPW', '₩'],
        ['KRW', '₩'],
        ['KGS', 'лв'],
        ['LAK', '₭'],
        ['LVL', 'Ls'],
        ['LBP', '£'],
        ['LRD', '$'],
        ['LTL', 'Lt'],
        ['MKD', 'ден'],
        ['MYR', 'RM'],
        ['MUR', '₨'],
        ['MXN', '$'],
        ['MNT', '₮'],
        ['MZN', 'MT'],
        ['NAD', '$'],
        ['NPR', '₨'],
        ['ANG', 'ƒ'],
        ['NZD', '$'],
        ['NIO', 'C$'],
        ['NGN', '₦'],
        ['NOK', 'kr'],
        ['OMR', '﷼'],
        ['PKR', '₨'],
        ['PAB', 'B/.'],
        ['PYG', 'Gs'],
        ['PEN', 'S/.'],
        ['PHP', '₱'],
        ['PLN', 'zł'],
        ['QAR', '﷼'],
        ['RON', 'lei'],
        ['RUB', 'руб'],
        ['SHP', '£'],
        ['SAR', '﷼'],
        ['RSD', 'Дин.'],
        ['SCR', '₨'],
        ['SGD', '$'],
        ['SBD', '$'],
        ['SOS', 'S'],
        ['ZAR', 'S'],
        ['LKR', '₨'],
        ['SEK', 'kr'],
        ['CHF', 'CHF'],
        ['SRD', '$'],
        ['SYP', '£'],
        ['TWD', 'NT$'],
        ['THB', '฿'],
        ['TTD', 'TT$'],
        ['TRL', '₤'],
        ['TVD', '$'],
        ['UAH', '₴'],
        ['GBP', '£'],
        ['USD', '$'],
        ['UYU', '$U'],
        ['UZS', 'лв'],
        ['VEF', 'Bs'],
        ['VND', '₫'],
        ['YER', '﷼'],
        ['ZWD', 'Z$'],
        ['BHD', 'BD'],
        ['XOF', 'CFA'],
        ['AOA', 'Kz'],
        ['DZD', 'DA'],
        ['AMD', '֏'],
        ['BYN', 'Br'],
        ['BDT', '৳'],
        ['BIF', 'FBu'],
        ['CVE', 'Esc.'],
        ['XAF', '₣'],
        ['KMF', '₣'],
        ['DJF', '₣'],
        ['AED', 'DH'],
        ['ERN', 'Nfk'],
        ['ETB', 'Br'],
        ['GMD', 'D'],
        ['GEL', '₾'],
        ['GHS', '₵'],
        ['GNF', '₣'],
        ['HTG', 'G'],
        ['IQD', 'ع.د'],
        ['XPF', '₣'],
        ['JOD', 'د.ا'],
        ['KES', 'Sh'],
        ['KWD', ''],
        ['LSL', 'L'],
        ['LYD', 'ل.د'],
        ['MOP', 'P'],
        ['MGA', 'MK'],
        ['MWK', ''],
        ['MVR', 'ރ'],
        ['MAD', 'د.م.'],
        ['MRU', 'UM'],
        ['MDL', 'L'],
        ['MMK', ''],
        ['PGK', 'K'],
        ['CDF', '₣'],
        ['RWF', '₣'],
        ['WST', ''],
        ['STN', 'Db'],
        ['SLL', 'Le'],
        ['SZL', 'L'],
        ['SDG', '£'],
        ['SSP', ''],
        ['TJS', 'ЅМ'],
        ['TZS', 'Sh'],
        ['TOP', 'T$'],
        ['TMT', 'm'],
        ['TRY', ''],
        ['TND', 'د.ت'],
        ['UGX', 'Sh'],
        ['VUV', 'Vt'],
        ['VES', 'ރ'],
        ['ZMW', 'ZK'],
        ['ZWL', '$']
    ];

    public static function fromIso4217Code(Iso4217Code $code): array
    {
        foreach (static::$data as $currency) {
            if ($code->equals(new Iso4217Code($currency[0]))) {
                return $currency;
            }
        }
        return [];
    }

    public static function iso4217Codes(): array
    {
        return array_map(fn(array $item): string => $item[0], static::$data);
    }

    public static function data(): array
    {
        return static::$data;
    }
}
